server:
  port: 6868
eureka:
  client:
    register-with-eureka: false # 不将自己注册到Eureka服务中
    fetch-registry: false # 是否从Eureka中获取注册信息
    service-url:
      defalutZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
spring:
  security:
    user:
      name: leon
      password: 970410
