server:
  port: 9008
spring:
  profiles:
    active: dev
  application:  
    name: sdcommunity-user #指定服务名
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: sdcommunity
    ttl: 604800000 # 一周过期
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://leon:970410@119.3.177.76:6868/eureka/