server:
  port: 9008
spring:
  profiles:
    active: dev
  application:  
    name: sdcommunity-user #指定服务名
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: sdcommunity
    ttl: 600000 # 10分钟过期