server:
  port: 9003
spring:
  application:
    name: sdcommunity-qa
  jpa:
    database: mysql
    show-sql: true
  profiles:
    active: dev
jwt:
  config:
    key: sdcommunity
    ttl: 604800000 # 一周过期