server:
  port: 9003
spring:
  application:
    name: sdcommunity-qa
  jpa:
    database: mysql
    show-sql: true
  profiles:
    active: dev
jwt:
  config:
    key: sdcommunity
    ttl: 604800000 # 一周过期
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
# 熔断器
feign:
  hystrix:
    enabled: true